### ISSUE TITLE
Broken with latest version of node-fetch 

### ISSUE THREAD

**Issue by madeleineostoja** [rh389/codegen-prismic-fetch#4]
`node-fetch` v3 is now an ES module, and trying to `require` it throws an exception. Need to either lock node-fetch at v2 major, which is good practice anyway (is there a reason the library requires `>=` of `node-fetch`?) or update to ESM import syntax.

**Comment by gracjan-op** [comment]
Yes - i have a same problem here.

**Comment by robhogan** [comment]
Thanks - now locked to v2 and published in 1.0.5. We'll switch to ESM import syntax in the next major version but this is the right fix for now.

(I've no idea why I used `>=` in the first place!)
